### ISSUE TITLE
Fields in web_connectivity test sometimes missing

### ISSUE THREAD

**Issue by hellais** [measurement-kit/measurement-kit#1183]
It seems like web_connectivity tests will sometimes miss the keys `queries` and `tcp_connect` will be empty.

For queries it could be due to the dns template not parsing the nameserver properly: https://github.com/measurement-kit/measurement-kit/blob/b25b1882d5d45c1422591c638f2c41a47dcd19a2/src/libmeasurement_kit/net/utils.cpp.

As of now I have only managed to reproduce it once on ooniprobe-ios 1.1.3 and from the Abraxas network.

**Comment by bassosimone** [comment]
@hellais I think this has been fixed in master and stable. Specifically, the changesenabling this are part of master and #1231 that should land in stable as soon as travis terminates successfully.

I'd say we test a bit the apps (including v0.6.2 that is basically the latest stable release since v0.6.3 just fixes regress tests) and, unless the problem persists, we can close this issue.

**Comment by bassosimone** [comment]
I guess we can now close this issue. I remember spending a morning making sure that the output format of MK matches as closely as possible the one of ooni-probe. Including fixing this issue.
