### ISSUE TITLE
http: improve the client interface

### ISSUE THREAD

**Issue by hellais** [measurement-kit/measurement-kit#1208]
In implementing the orchestrator client I find myself writing a bunch of boilerplate code and I think this would be much easier if we were to provide a better http client abstraction.

I will use this issue to take some notes on what I would like to improve, though maybe not do it immediately as I suspect it may break things.

* The `mk::http::Response` response struct could have some methods useful for decoding JSON. However in order to do this we would have to make it into a class (question: would changing it from struct to class break many things?).
Methods I would like it to have include `ErrorOr<json> json()`, that would try to decode as JSON the body and include the big `try, catch` chain we use in many places

* There should be more high level abstractions for every http method (`http::post`, `http::put`, etc.), we currently only have one for `get`

* There should be a way for me to pass a json object and have the client take care of serializing it and maybe setting the `Content-Type` header.

Some things to draw inspiration from include:

* http://docs.python-requests.org/
* https://github.com/whoshuu/cpr
* https://github.com/mrtazz/restclient-cpp

**Comment by bassosimone** [comment]
>    The mk::http::Response response struct could have some methods useful for decoding JSON.

Yes, that would be very useful.

> However in order to do this we would have to make it into a class

You can also add methods to a `class`. For C++ a `struct` with methods is a class with `public` default visibility. In general, I try to follow the pattern that I've read somewhere (I guess inside of thinking in C++) to use `struct` when it really looks like a C struct and `class` when we have methods.

> (question: would changing it from struct to class break many things?).

No, I don't think changing it from `struct` to `class` (or just adding methods to `struct` will break any thing. What would change is for sure the ABI because we pass from a [POD](http://en.cppreference.com/w/cpp/concept/PODType) to a data type with methods.

>    Methods I would like it to have include ErrorOr<json> json(), that would try to decode as JSON the body and include the big try, catch chain we use in many places

Yes, that would be very useful.

>    There should be more high level abstractions for every http method (http::post, http::put, etc.), we currently only have one for get

Yes, this also would be very useful.

>    There should be a way for me to pass a json object and have the client take care of serializing it and maybe setting the Content-Type header.

Yes, perhaps some even higher level abstraction for sending / receiving JSON. (Like, ideally when you invoke APIs you typically want to `http::json::post(json_request, /* ... */, [=](Error err, json_response)` no?)

I think that the proposed changes will be great because it will allow us to factor out common code that we've been using in the many places in which we call APIs. I feel like the proper way to proceed with this would be to add all the abstraction you are talking about plus the last one I mentioned (i.e. a function for sending and receiving JSON). This would allow the programmer to express what he/she wants without even bothering with the details of how to do that (decode json, check and route errors).

**Comment by bassosimone** [comment]
This has landed in the integration branch for v0.7.0 as b96e9fd5e8f2101e8485fe8955c5c43e2875f91a, 58623e46e863bb69b9de7f66b69d0a18a3706f17 and f3dcf7e398ab0460d370f9ab23e5d99ba180e296. Closing the issue.
