### ISSUE TITLE
Don't bump soname on every new release

### ISSUE THREAD

**Issue by irl** [measurement-kit/measurement-kit#1340]
If possible can the bumps on the soname be happening less often?

**Comment by bassosimone** [comment]
Yes, we can be less conservative than now. Currently, I'm bumping it at any release because I've read in the past that maintaining ABI compatibility for C++ is quite hard (cannot find the link now, tho).

A possible solution to mitigate the issue of ABI compatibility maybe be, probably, to have &mdash; where possible &mdash; inline code in headers. This is actually quite common in C++ (there are even libraries that are headers only, even though in such case they're mostly templates). The advantage of this approach would be that we can change the API (easier to track) and not the ABI.

**Comment by bassosimone** [comment]
@irl I think I am converging on a strategy for this, but it will not be part of MK soon-ish. It will probably land in 1-2 minor releases after some refactoring of headers to reduce amount of public stuff.

After that, I believe it would be easy to keep ABI stable (I think it would probably be possible to avoid bumping the ABI unless there are really major changes in the library).

**Comment by irl** [comment]
Thanks for looking at this. (: This sounds entirely reasonable.

**Comment by bassosimone** [comment]
We're not going to add MK to Debian, so it doesn't matter for now.
