### ISSUE TITLE
Perform HTTP request using DNS response from the control

### ISSUE THREAD

**Issue by hellais** [measurement-kit/measurement-kit#1393]
It was suggested that we may want to use the control DNS response to do the connect in web_connectivity instead of resolving it again and potentially being spoofed again.

**Comment by bassosimone** [comment]
Do you think this should be something that we can configure or just the new default?

**Comment by bassosimone** [comment]
I think this can land in v0.9.0.

**Comment by fortuna** [comment]
The main rationale behind the initial request was that, if a site is dns poisoned, we are not getting much information by fetching data from the bogus address. We get more information if we find out whether we would be able to fetch data correctly if DNS poisoning was fixed.

However, after spending quite some time looking at OONI web_connectivity data, I realized that there are many DNS false positives due to a weak control. For example, OONI shows inconsistency even if the control fails or if there are geographical differences. So we may actually be fetching data from a legit server!

Many of the DNS inconsistencies end up being "saved" by a successful http-diff, since OONI says blocking: false in that case. This reduces the rate of DNS false positives.

If we use the control IP to fetch the page, then we lose this second validation of the DNS reposnse. For that reason, it may be worth to keep the existing behavior. Using the control IP could be in addition to using the experiment IP.

Thoughts?

**Comment by bassosimone** [comment]
>  [...] For that reason, it may be worth to keep the existing behavior. Using the control IP could be in addition to using the experiment IP.

Thanks for all your research. I missed the comment up until now, sorry about that. I believe the right way to proceed is to retain the current behaviour for now.

> Using the control IP could be in addition to using the experiment IP.

This seems to me a rational way to improve the test.

**Comment by bassosimone** [comment]
I believe we can close this issue now. In addition to what @fortuna said, i.e. that the control is weak, we have this additional issue that we want to reduce coupling between measuring and performing analysis. This specifically means we don't want any bit of WebConnectivity, except the final result that determines blocking, to depend on the test helper. Ideally, we could run a measurement, talk to the test helper at a later time, and then assemble and submit a WebConnectivity report.
