### ISSUE TITLE
Add support for follow-up measurements

### ISSUE THREAD

**Issue by hellais** [measurement-kit/measurement-kit#1422]
This would mean that when we detect something with a certain test, we should have support for defining logic for triggering some other tests conditionally.

**Comment by willscott** [comment]
This probably would be okay initially as a hard-coded special case where detected anomalies in the web_connectivity test trigger the host field manipulation test on those domains.

**Comment by hellais** [comment]
I also filed https://github.com/TheTorProject/ooni-spec/issues/92 that is some data format changes that would probably need to happen to make this easier.

**Comment by bassosimone** [comment]
@willscott yay, but I in the long term I think it would be interesting to give the apps some way of controlling what follow-up measurements are triggered. It seems to me that, for example, user facing settings may influence what kind of follow up measurements you run. Also, honestly, I'd really like to separate engine and rules, because it seems to me MK gotta be the engine and rules may change more frequently.

**Comment by bassosimone** [comment]
This will be done in https://github.com/ooni/probe-engine/issues/73
