### ISSUE TITLE
Report_id is not included in the on_entry callback

### ISSUE THREAD

**Issue by hellais** [measurement-kit/measurement-kit#1462]
When I register the `on_entry` callback, I would expect the report_id to appear in the entry, but instead that field is missing.

**Comment by bassosimone** [comment]
Yes. The reason why this is so is that the report ID is hidden inside the specific class that talks with the OONI backend and is patched into the report only when the report is emitted on the wire.

The need to have the correct report ID inside the report emitted by the callback is more than reasonable and I believe MK should be fixed to this end. I cannot do that as part of v0.8.0, tho, because it seems to me this requires some refactoring that I'd like to do with more clam.

Hence, v0.9.0. Okay?

**Comment by hellais** [comment]
> Hence, v0.9.0. Okay?

Sure, that works.

**Comment by hellais** [comment]
I would also like to know if the report has failed to be opened and hence there is no `report_id` to reference.
