### ISSUE TITLE
Measure timing information using a monotonic clock

### ISSUE THREAD

**Issue by hellais** [measurement-kit/measurement-kit#1613]
I think this is particularly relevant to: https://github.com/measurement-kit/measurement-kit/issues/1414, but it would also avoid issues that arise when the system clock changes (due to daylight savings or it ticking forward due to an NTP update).

Currently in MK we use the wallclock as a timestamp to determine, for example, the `test_runtime`. Instead we should probably use something like the linux `CLOCK_MONOTONIC` to determine the time deltas for all timing related information.

Here are some possibly useful links to look at for this:
* https://groups.google.com/forum/#!msg/golang-nuts/D11F4zMs-E0/Nnh6W6nN-3YJ
* https://github.com/davecheney/junk/blob/master/clock/clock_linux.go
* https://github.com/golang/go/blob/master/src/time/time.go#L10
* macos: https://stackoverflow.com/questions/5167269/clock-gettime-alternative-in-mac-os-x/21352348#21352348
* windows: https://msdn.microsoft.com/en-us/library/ms724408(VS.85).aspx

**Comment by bassosimone** [comment]
There is a monotonic clock in C++11, so we should actually use it. Trying to use the system monotonic clock is more complex because we need to have a different interface for each system.

(FWIW, [I've started doing it in the simplified libndt on which I'm working](https://github.com/measurement-kit/libndt/blob/c726df64a0a9cf75f228cf5701a1605f6a4e35fe/libndt.cpp#L436)).

Thanks for prodding us in the right direction here.

**Comment by bassosimone** [comment]
Mentioned this issue where relevant in the ooni/probe-engine: https://github.com/ooni/probe-engine/issues/12. Note that Go uses a monotonic clock by default, so we're already good.
