### ISSUE TITLE
Please Add Support for tvOS 

### ISSUE THREAD

**Issue by anilsolanki06** [measurement-kit/measurement-kit#1622]
I have successfully run the iOS framework on Apple TV simulator, But I am running on real device Apple TV then it is failing. Following linker error is coming. Please help on it.

**measurement_kit.framework/measurement_kit(ndt.o), building for tvOS, but linking in object file built for iOS, for architecture arm64**

I am just a new developer so please ignore if I am not good at it.

**Comment by bassosimone** [comment]
We were considering considering bitcode for the future, but never invested enough time into making it possible yet. We have some documentation on how this could be done in #658. Since then, things have changed a little bit, but the theory that one should pass `-fembed-bitcode` still holds.

What for now fails me is: since bitcode is LLVM intermediate representation, I would assume that one should compile targeting bitcode _twice_. Once for 32 bit and then for 64 bit. Correct?

**Comment by bassosimone** [comment]
I'm afraid this is not going to happen as we don't have capacity to do that. Those who wish to use MK for running network performance tests, and specifically NDT, should consider using the next generation NDT implementation, ndt7, instead. As of this writing, this implementation is still in beta, but we're quickly moving towards stable. In particular, there is an implementation of ndt7 that is written in Swift and is meant to also run quite easily on TvOS: https://github.com/m-lab/ndt7-client-ios
