### ISSUE TITLE
measurement-kit v0.10.0: asn.mmdb and country.mmdb location 

### ISSUE THREAD

**Issue by ja-pa** [measurement-kit/measurement-kit#1771]
Hi,
I'm testing measurement-kit v0.10.0 on OpenWrt and there is a problem with locating **asn.mmdb** and **country.mmdb** files (see log below).
If I run measuremnt_kit from directory where are these DB files located, everything work as expected. So I'm not sure if I missed any option during measurement-kit compilation or where the problem is.

Is there any option where I can hardcode path for measurement_kit app?

_running from /_
```
 root@turris:~# measurement_kit dash
Contacting bouncer: https://bouncer.ooni.io
Using discovered collector: https://c.collector.ooni.io:443
[!] mmdb_open('country.mmdb'): Error opening the specified MaxMind DB file
[!] mmdb_open('asn.mmdb'): Error opening the specified MaxMind DB file
[!] mmdb_open('asn.mmdb'): Error opening the specified MaxMind DB file
Your country: ZZ
Your ISP identifier: AS0
Your ISP name: 
```

_running from /usr/lib (where is asn.mmdb and country.mmdb)_
```
root@turris:/usr/lib# measurement_kit dash
Contacting bouncer: https://bouncer.ooni.io
Using discovered collector: https://c.collector.ooni.io:443
Your country: CZ
Your ISP identifier: ***** (removed but is ok)
Your ISP name: *****(removed but is ok)
```

**Comment by bassosimone** [comment]
You didn't miss anything. The `measurement_kit` binary assumes that these files are in the current working directory. Because our main use case is integration of the library, we never spent too much energy in making the `measurement_kit` client super pleasant to use.

A workaround that I would recommend, if your use case supports that, is to download these files in the directory in which you want to run it. This is a bit of a bummer but works out of the box.

**Comment by ja-pa** [comment]
Ok, understand. Thank you for clarification :-)

**Comment by bassosimone** [comment]
Moving this issue to MK v0.11.x. We can add command line options quite easily.
