### ISSUE TITLE
IP scrubbing not working as intended in some unclear cases (very limited impact, related to app settings, and to other corner cases)

### ISSUE THREAD

**Issue by anadahz** [measurement-kit/measurement-kit#1789]
It seems that this [function](https://github.com/measurement-kit/measurement-kit/blob/62d477f085f767bc8235f04ad08dedd32a03afc6/src/libmeasurement_kit/ooni/utils.cpp#L38) doesn't always "sanitize" detected probe's IP with the `[REDACTED]` string.

For obvious reasons I'm not including the list of measurements with IP leaks on this ticket. Please find an email to `contact@openobservatory.org` with a list of measurements found with IP leaks.

Edit: Emailed some more headers

**Comment by bassosimone** [comment]
The `scrub` function just replaces occurrences of `real_probe_ip` with `[SCRUBBED]` in the input string `s`. The issue you describe may be related to on of the following cases:

1. the IP address that we discover is different from the IP address in the header hence the sanitisation step fails because the string we are searching for is not found

2. there is some place in the code where we should be calling `scrub()` and we don't

It also probably depends on the experiments being run. I'll do some testing to understand under what conditions that problem that you described in private happens. I'll report back as soon as I know.

Thank you for investigating this issue. But also not-thank-you for reporting it this way. I believe the proper way to report this kind of issues involving PII leaks or nasty bugs is:

1. either go for a full disclosure and post the full details here, such that the issue is immediately actionable by developers and crystal clear to anyone who may be concerned

2. contact us in private and make it clear that you would go for full disclosure if we do not react quickly enough to the issue that you reported (I think 90 days is common)

I do not like a bit the approach that you chose. Persons landing here would see that there is an issue but cannot see the discussion related to understanding whether this is a bug, what is triggering it, under what specific conditions, what could be its impact etc. They would know that there is a bug, and this may be scary, but they would not have factual data to understand its implications. I would rather see a situation where full information is provided, whether immediately, or when the issue has been solved. And I believe both scenarios, immediate full disclosure and responsible disclosure, are likely to put as much pressure on us as put by this disclosure strategy that you're using. So I'd really be happy to see a different strategy being used by you, or anyone else, next time.

**Comment by bassosimone** [comment]
Removed the `help wanted` label because the only person that can help me at this point is @anadahz and he knows it, since we communicated across many channels, so the label is redundant.

**Comment by bassosimone** [comment]
Changed also the title of the issue. As I mentioned in private to @anadahz and others, we should try to measure the percentage impact of this issue and try to find out what specific condition(s) could be the trigger for this issue. Maybe all these cases have something in common?

**Comment by bassosimone** [comment]
Also, as a lesson learned for myself, and as a public form of self criticism, I should always acknowledge bugs that are discussed in private. This is actually where a non-full-disclosure workflow has failed me and hence I guess this is why my preference is generally for going for a full disclosure.

**Comment by bassosimone** [comment]
So, I deployed the following code on a GCE box:

```Go
package main
import (
        "fmt"
        "log"
        "net/http"
        "strings"
)
func main() {
        http.HandleFunc("/", func(w http.ResponseWriter, r *http.Request) {
                ip := strings.Split(r.RemoteAddr, ":")[0]
                w.Header().Add("X-Client-IP", ip)
                w.Write([]byte(fmt.Sprintf(`{"ip": "%s"}`, ip)))
        })
        if err := http.ListenAndServe(":80", nil); err != nil {
                log.Fatal(err)
        }
}
```

This is what I can when running `measurement_kit` with this service:

```json
{
    "annotations": {
        "engine_name": "libmeasurement_kit",
        "engine_version": "0.10.3",
        "engine_version_full": "v0.10.3",
        "platform": "macos"
    },
    "data_format_version": "0.2.0",
    "id": "2934666d-d85f-4fbd-8260-7c0f8f35e849",
    "input": "http://35.204.49.125/",
    "input_hashes": [],
    "measurement_start_time": "2019-05-07 17:40:05",
    "options": [],
    "probe_asn": "AS30722",
    "probe_cc": "IT",
    "probe_city": null,
    "probe_ip": "127.0.0.1",
    "report_id": "20190507T174005Z_AS30722_VT4slYBd4e8lGP1ESj5Ho62Agnfc02VGeNSo0b01htwmteATZO",
    "software_name": "measurement_kit",
    "software_version": "0.10.3",
    "test_helpers": {
        "backend": {
            "address": "https://b.web-connectivity.th.ooni.io:443",
            "type": "https"
        }
    },
    "test_keys": {
        "accessible": false,
        "agent": "redirect",
        "blocking": "dns",
        "body_length_match": null,
        "body_proportion": 0.0,
        "client_resolver": "91.80.37.85",
        "control": {
            "dns": {
                "addrs": [],
                "failure": "dns_server_failure"
            },
            "http_request": {
                "body_length": -1,
                "failure": "connection_refused_error",
                "headers": {},
                "status_code": -1
            },
            "tcp_connect": {
                "35.204.49.125:80": {
                    "failure": "connection_refused_error",
                    "status": false
                }
            }
        },
        "control_failure": null,
        "dns_consistency": "inconsistent",
        "dns_experiment_failure": null,
        "headers_match": null,
        "http_experiment_failure": null,
        "requests": [
            {
                "failure": null,
                "request": {
                    "body": "",
                    "headers": {
                        "Accept": "text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8",
                        "Accept-Language": "en-US;q=0.8,en;q=0.5",
                        "User-Agent": "Mozilla/5.0 (Windows NT 6.1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/47.0.2526.106 Safari/537.36"
                    },
                    "method": "GET",
                    "tor": {
                        "exit_ip": null,
                        "exit_name": null,
                        "is_tor": false
                    },
                    "url": "http://35.204.49.125/"
                },
                "response": {
                    "body": "{\"ip\": \"[REDACTED]\"}",
                    "code": 200,
                    "headers": {
                        "Content-Length": "24",
                        "Content-Type": "text/plain; charset=utf-8",
                        "Date": "Tue, 07 May 2019 17:40:06 GMT",
                        "X-Client-Ip": "[REDACTED]"
                    },
                    "response_line": "HTTP/1.1 200 OK"
                }
            }
        ],
        "retries": null,
        "socksproxy": null,
        "status_code_match": null,
        "tcp_connect": [
            {
                "ip": "35.204.49.125",
                "port": 80,
                "status": {
                    "blocked": false,
                    "failure": null,
                    "success": true
                }
            }
        ],
        "title_match": null
    },
    "test_name": "web_connectivity",
    "test_runtime": 0.38925981521606445,
    "test_start_time": "2019-05-07 17:40:03",
    "test_version": "0.0.1"
}
```

Apart from interesting issues in contacting the server using the test helper, it seems that the data in the resulting JSON is correctly redacted. So, in this simple case scrubbing is working.

This is interesting because it stems my current mental model of the issue needs to be improved.

**Comment by bassosimone** [comment]
So, this is iOS:

```json
{
 "data_format_version" : "0.2.0",
 "software_version" : "2.1.0-beta.1",
 "annotations" : {
   "engine_name" : "libmeasurement_kit",
   "engine_version_full" : "v0.10.1",
   "platform" : "ios",
   "engine_version" : "0.10.1",
   "network_type" : "wifi"
 },
 "test_helpers" : {
   "backend" : {
     "address" : "https:\/\/c.web-connectivity.th.ooni.io:443",
     "type" : "https"
   }
 },
 "options" : [

 ],
 "test_name" : "web_connectivity",
 "test_version" : "0.0.1",
 "probe_cc" : "IT",
 "input" : "http:\/\/35.204.49.125\/",
 "input_hashes" : [

 ],
 "probe_ip" : "109.116.253.12",
 "id" : "2f893c70-4389-48b4-ad7c-654dc3ec7473",
 "report_id" : "",
 "probe_city" : null,
 "test_keys" : {
   "status_code_match" : true,
   "blocking" : false,
   "control" : {
     "dns" : {
       "addrs" : [

       ],
       "failure" : "dns_server_failure"
     },
     "tcp_connect" : {
       "35.204.49.125:80" : {
         "failure" : null,
         "status" : true
       }
     },
     "http_request" : {
       "failure" : null,
       "headers" : {
         "content-encoding" : "",
         "X-Client-Ip" : "37.218.241.164",
         "Date" : "Tue, 07 May 2019 18:01:31 GMT",
         "Content-Type" : "text\/plain; charset=utf-8"
       },
       "body_length" : 24,
       "status_code" : 200,
       "title" : ""
     }
   },
   "dns_consistency" : "inconsistent",
   "requests" : [
     {
       "failure" : null,
       "request" : {
         "body" : "",
         "method" : "GET",
         "headers" : {
           "Accept-Language" : "en-US;q=0.8,en;q=0.5",
           "User-Agent" : "Mozilla\/5.0 (Windows NT 6.1) AppleWebKit\/537.36 (KHTML, like Gecko) Chrome\/47.0.2526.106 Safari\/537.36",
           "Accept" : "text\/html,application\/xhtml+xml,application\/xml;q=0.9,*\/*;q=0.8"
         },
         "url" : "http:\/\/35.204.49.125\/",
         "tor" : {
           "exit_ip" : null,
           "exit_name" : null,
           "is_tor" : false
         }
       },
       "response" : {
         "body" : "{\"ip\": \"109.116.253.12\"}",
         "code" : 200,
         "headers" : {
           "X-Client-Ip" : "109.116.253.12",
           "Date" : "Tue, 07 May 2019 18:01:30 GMT",
           "Content-Length" : "24",
           "Content-Type" : "text\/plain; charset=utf-8"
         },
         "response_line" : "HTTP\/1.1 200 OK"
       }
     }
   ],
   "accessible" : true,
   "title_match" : true,
   "http_experiment_failure" : null,
   "control_failure" : null,
   "body_proportion" : 1,
   "tcp_connect" : [
     {
       "ip" : "35.204.49.125",
       "status" : {
         "blocked" : false,
         "failure" : null,
         "success" : true
       },
       "port" : 80
     }
   ],
   "headers_match" : true,
   "agent" : "redirect",
   "retries" : null,
   "socksproxy" : null,
   "body_length_match" : true,
   "dns_experiment_failure" : null,
   "client_resolver" : "91.80.37.82"
 },
 "measurement_start_time" : "2019-05-07 18:01:30",
 "test_runtime" : 2.0995841026306152,
 "probe_asn" : "AS30722",
 "test_start_time" : "2019-05-07 18:01:27",
 "software_name" : "ooniprobe-ios"
}
```

**Comment by bassosimone** [comment]
So, let's now try again by disabling the option of sharing my IP address:

```json
{
    "annotations": {
        "engine_name": "libmeasurement_kit",
        "engine_version": "0.10.1",
        "engine_version_full": "v0.10.1",
        "network_type": "wifi",
        "platform": "ios"
    },
    "data_format_version": "0.2.0",
    "id": "de8a8d6c-e68a-4e44-a1d3-5e2e523aaac3",
    "input": "http://35.204.49.125/",
    "input_hashes": [],
    "measurement_start_time": "2019-05-07 18:10:52",
    "options": [],
    "probe_asn": "AS30722",
    "probe_cc": "IT",
    "probe_city": null,
    "probe_ip": "127.0.0.1",
    "report_id": "",
    "software_name": "ooniprobe-ios",
    "software_version": "2.1.0-beta.1",
    "test_helpers": {
        "backend": {
            "address": "https://b.web-connectivity.th.ooni.io:443",
            "type": "https"
        }
    },
    "test_keys": {
        "accessible": true,
        "agent": "redirect",
        "blocking": false,
        "body_length_match": true,
        "body_proportion": 1,
        "client_resolver": "91.80.37.87",
        "control": {
            "dns": {
                "addrs": [],
                "failure": "dns_server_failure"
            },
            "http_request": {
                "body_length": 24,
                "failure": null,
                "headers": {
                    "Content-Type": "text/plain; charset=utf-8",
                    "Date": "Tue, 07 May 2019 18:10:53 GMT",
                    "X-Client-Ip": "37.218.242.234",
                    "content-encoding": ""
                },
                "status_code": 200,
                "title": ""
            },
            "tcp_connect": {
                "35.204.49.125:80": {
                    "failure": null,
                    "status": true
                }
            }
        },
        "control_failure": null,
        "dns_consistency": "inconsistent",
        "dns_experiment_failure": null,
        "headers_match": true,
        "http_experiment_failure": null,
        "requests": [
            {
                "failure": null,
                "request": {
                    "body": "",
                    "headers": {
                        "Accept": "text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8",
                        "Accept-Language": "en-US;q=0.8,en;q=0.5",
                        "User-Agent": "Mozilla/5.0 (Windows NT 6.1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/47.0.2526.106 Safari/537.36"
                    },
                    "method": "GET",
                    "tor": {
                        "exit_ip": null,
                        "exit_name": null,
                        "is_tor": false
                    },
                    "url": "http://35.204.49.125/"
                },
                "response": {
                    "body": "{\"ip\": \"[REDACTED]\"}",
                    "code": 200,
                    "headers": {
                        "Content-Length": "24",
                        "Content-Type": "text/plain; charset=utf-8",
                        "Date": "Tue, 07 May 2019 18:10:53 GMT",
                        "X-Client-Ip": "[REDACTED]"
                    },
                    "response_line": "HTTP/1.1 200 OK"
                }
            }
        ],
        "retries": null,
        "socksproxy": null,
        "status_code_match": true,
        "tcp_connect": [
            {
                "ip": "35.204.49.125",
                "port": 80,
                "status": {
                    "blocked": false,
                    "failure": null,
                    "success": true
                }
            }
        ],
        "title_match": true
    },
    "test_name": "web_connectivity",
    "test_runtime": 1.2090590000152588,
    "test_start_time": "2019-05-07 18:10:50",
    "test_version": "0.0.1"
}
```

So, in this case, instead, this is what happens:

1. the IP is redacted in the response headers and body

2. we still have the `X-Client-IP` in the control

**Comment by bassosimone** [comment]
Actionable items so far (which should probably become issues):

1. we see a weird `X-Client-IP` in the control which is unrelated to my IP

2. we do not scrub my IP when we tell MK we're fine with publishing it (is this a bug?)

3. we do not redact the response from the control (I'm quite sure about this and, even though this is not a real problem in this case, it's certainly a nice improvement to add)

**Comment by bassosimone** [comment]
So, with respect to:

> we do not scrub my IP when we tell MK we're fine with publishing it (is this a bug?)

I spent a bit more time thinking about this and it's clearly not a bug. We're including the IP in any case in the JSON, so I don't really see why we should scrub it from somewhere else.

**Comment by anadahz** [comment]
> either go for a full disclosure and post the full details here, such that the issue is immediately actionable by developers and crystal clear to anyone who may be concerned

@bassosimone I don't feel that it's nice or needed to make publicly available PII data from OONI reports. You should have already the PII details as they were sent to `contact@openobservatory.org`.
I hope you don't make them public or at least not before an action has defined.

> contact us in private and make it clear that you would go for full disclosure if we do not react quickly enough to the issue that you reported (I think 90 days is common)

I have raised the issue of PII sensitive data since November 2017 in many private conversations and on the following issues:
https://github.com/measurement-kit/measurement-kit/issues/1473
https://github.com/ooni/probe/issues/780

You can also find more information and discussion about the PII data in:
https://github.com/measurement-kit/measurement-kit/issues/1476
https://github.com/ooni/backend/issues/671

I even asked again about progress on the PII data issue in [December 2018](https://github.com/ooni/backend/issues/671), so I'm not sure in which way I should have reported the PII data issues.

Perhaps you may want to provide some more information on how people should disclose security/privacy issues related to OONI.

**Comment by bassosimone** [comment]
>> either go for a full disclosure and post the full details here, such that the issue is immediately actionable by developers and crystal clear to anyone who may be concerned
>
> @bassosimone I don't feel that it's nice or needed to make publicly available PII data from OONI reports. You should have already the PII details as they were sent to contact@openobservatory.org.
I hope you don't make them public or at least not before an action has defined.

You are quoting me out of context. This is one option; responsible disclosure the other. Given your stated objectives, I think the next time you should definitely use responsible disclosure.

Speaking of the email to contact@openobservatory.org, I just see one email that I cannot decrypt since it's not encrypted with the contact@openobservatory.org PGP key I'm aware of. I may also possibly have missed other emails, in which case I apologise for that.

>> contact us in private and make it clear that you would go for full disclosure if we do not react quickly enough to the issue that you reported (I think 90 days is common)
>
> I have raised the issue of PII sensitive data since November 2017 in many private conversations and on the following issues:
> [snip]
> I even asked again about progress on the PII data issue in December 2018, so I'm not sure in which way I should have reported the PII data issues.

I believe there is a misunderstanding. I'm not discussing the general PII data issue here. My comment is focused *on this specific issue*. Since you claimed to have found a bug in a scrubbing function inside of MK, and since that apparently had PII implications, this specific issue should either have been under full disclosure or under responsible disclosure. The previous conversation regarding PII does not give you, or anyone else, a blank check for not behaving according to the books.

Especially because the correct process is the following:

1. if you're doing full disclosure, you do the full research and publish exactly where we're leaking PII so you can claim that we're leaking PII and you claim is based on facts, and then it would be my duty to go through the evidence that you provided, validate, it develop fixes

2. if you're doing responsible disclosure, we should probably cooperate to understand whether it's a PII leak, what is its impact, and how to mitigate it before writing "PII leaks" on an issue tracker

In this specific case, for example, if you see my comments above, it seems that scrubbing is working to some extent, that there may be corner cases where we can improve, but that what you call "PII leaks" may indeed be related to the app settings. So, if we had followed the correct process, anyone of the above, we could have ended up communicating the situation to users precisely.

Instead, the process used here led to claim PII leak without being sure, without presenting public evidence, where possibly that was not the case. We should probably discuss more, and you should show me, in private a this point, more instances of this bug. So, I can conclude whether this is related to the app settings, or is really a bug. But, as I said, this process should either have been fully in the open, or fully in secret within a reasonable per-bug deadline (e.g. ninety months).

To conclude, my point is that it's wrong to say "PII leaks" without evidence. Either say it explicitly and provide evidence, or work with me/us in private and _then_, when we're clear that there is a PII leak and we've worked on a fix for that bug, write it on an issue. (If you think about it, I've done some extensive work to investigate this issue after nine days, which I don't think is that bad.)

> Perhaps you may want to provide some more information on how people should disclose security/privacy issues related to OONI.

Sure. This is exactly the point of my comment, which was addressed not specifically at you but to anyone that needs to report any PII or security vulnerability in the future. Please, either use full disclosure or responsible disclosure. If want to use responsible disclosure, please be responsible and do not open a vague issue, claiming facts without evidence, rather just contact us about that specific issue and work with us to fix it. In both cases, as a general advice, help us answering questions aimed at better understanding, and hence more efficiently solving, the issue at hand.

Is my previous comment, and are my intentions, more clear now?

**Comment by bassosimone** [comment]
Change the title to clarify that it's unclear where this happens. I believe the best course of action is to actually proceed as follows:

1. create issues for all the problems found when investigating the issue

2. cooperate with @anadahz to see more instances of this bug

3. test whether the theory that it's related to the app settings makes sense

4. understand whether we should specially annotate the measurements in a way that it's clear to who is analysing the data that there is actually no leak in this case [*]

[*] In all honesty, if the issue is only related to app settings, I can really see how this can lead to some cognitive dissonance when analysing the data and of course this is another issue :-(.

**Comment by bassosimone** [comment]
I'd like to start wrapping up this issue, and to provide public information with respect to the private conversation that we have had. Yesterday, @hellais performed analysis of the data that we have and he concluded that 1K measurements over 9M include the `X-Client-IP` header (according to @anadahz the most offending header) and ~70% of these include the IP _because_ the user configured ooniprobe to not scrub the IP address. We're now looking into the remaining measurements, trying to understand the causes, and so far we've formulated two theories:

1. that the IP is not scrubbed because IP lookup failed (see #1818)

2. that the IP is not scrubbed because it changes during the test (see #1817)

I'd say this issue has been fruiful in terms of understanding how we could do better (even though, as I mentioned, I am not happy about the issue opening process and would like to see a better process in the future).

**Comment by bassosimone** [comment]
Since this issue has a very limited impact, I'm going to remove it from the toplevel kanban and just keep it into the v0.11.x kanban, which is already the focus of my work.

**Comment by hellais** [comment]
I have done more research into this issue to better quantify the problem.

I focused on looking at IP leaks being disclosed via the `X-Client-IP` header, which according to @anadahz was the most common header being used.

I looked at 14 104 246 measurements starting from January 2019. I limited by investigation to only measurements collected with ooniprobe iOS and Android and found 1453 measurements where the IP fields was not redacted (by contrast 8712 were redacted properly).
Of these 990 were not redacted because the user had opted into collecting their probe IP.

Of the remaining 463 measurements that should have in fact been redacted, I found that 50 were not redacted due to the IP lookup failing and 42 were for certain due to the probe IP changing during the testing sessions.

I manually then looked at some other cases and I suspect most of these cases are caused by the probe_ip changing during the testing session.

To conclude I believe that the best way to go about fixing this issue is addressing it at the source of the problem (i.e. IP lookup and detecting probe IP changes).

To this end I believe that the following github issues will address:

1. Making the IP lookup system more reliable and supporting also retry (we don't actually have an issue for retries): https://github.com/measurement-kit/measurement-kit/issues/1515
2. Detecting when the probe changes IP address and take some action (ex. do another ip lookup or interrupt the testing): https://github.com/ooni/probe/issues/828

I think that implementing these two solutions we will be able to reduce the rate at which these incidents occur and we can evaluate how effective the solution is by repeating the above measurements once the fix is rolled out.

**Comment by bassosimone** [comment]
> we don't actually have an issue for retries

Right. Now we have one: #1821. Thanks !

**Comment by bassosimone** [comment]
We have a strategy for a safety net scrubbing of the IP in probe-engine: https://github.com/ooni/probe-engine/issues/28. We have plans for a backend integration service to test that: https://github.com/ooni/probe-engine/issues/42. We have an open question regarding what to do if the IP changes during the test: https://github.com/ooni/probe/issues/828. We have an open question regarding what to do if IP lookup fails: https://github.com/ooni/probe/issues/879.

All the possible follow-up related to the originally raised issue have been captured. There is nothing more to do here, except to say thank you to @anadahz for raising the issue.
