### ISSUE TITLE
Invalid version number causes measurement submission to fail

### ISSUE THREAD

**Issue by lorenzoPrimi** [measurement-kit/measurement-kit#1859]
I released a version of OONI Probe iOS with
`#define RELEASE_NAME @"-RC.1"`
so
`2.1.0-RC.1`
and every measurement fails to upload and get an empty report_id.
This happened only now because the old version numbers were like `2.1.0-beta.2`

**Comment by bassosimone** [comment]
I guess we can relax, or even remove the client-side checks. The server would probably fail, but at least we would get a much more hard and understandable error.

**Comment by bassosimone** [comment]
On second thought, I believe it's better to keep the existing code as is. However, it was not obvious to us what was going on because no log was emitted. I'll change the code to emit a warning if passed an invalid entry (i.e. an entry whose fields do not match the expectation). This change should be enough to debug this kind of problems in the future, should there be a relapse.
