### ISSUE TITLE
gcc 5.2.0 shows warnings.

### ISSUE THREAD

**Issue by DavideAllavena** [measurement-kit/measurement-kit#204]
Compiling with `gcc` 5.2.0  in `Linux 4.2.3-1-ARCH` these warnings are shown:

```
src/traceroute/interface.cpp: In member function ‘measurement_kit::traceroute::ProbeResultMeaning measurement_kit::traceroute::ProbeResult::get_meaning()’:
src/traceroute/interface.cpp:77:72: warning: format ‘%d’ expects argument of type ‘int’, but argument 4 has type ‘measurement_kit::traceroute::ProbeResultMeaning’ [-Wformat=]
                            icmp_type, icmp_code, PRM_::GOT_REPLY_PACKET);
                                                                        ^
src/traceroute/interface.cpp:84:40: warning: format ‘%d’ expects argument of type ‘int’, but argument 4 has type ‘measurement_kit::traceroute::ProbeResultMeaning’ [-Wformat=]
                              m->meaning);
                                        ^
src/traceroute/interface.cpp:89:48: warning: format ‘%d’ expects argument of type ‘int’, but argument 4 has type ‘measurement_kit::traceroute::ProbeResultMeaning’ [-Wformat=]
                          icmp_code, PRM_::OTHER);
                                                ^
```

**Comment by bassosimone** [comment]
The proper solution to fix this warning is the following:

1) modify the `ProbeResultMeaning` enum class to [explicitly specify its base type and size](http://stackoverflow.com/questions/12125637/can-i-define-the-size-of-an-enum-in-c). In this case I'd go for `int`, since that was already implied.

2) after that, `static_cast<int>(m->meaning)` or `PRM_::OTHER` should allow for safe conversion of the enum class type and suppress the warning.

Thanks for reporting this warning! I didn't noticed it, because on my Ubuntu system I use an older version of G++.

**Comment by DavideAllavena** [comment]
this warning is now shown many times:

`warning: ‘template<class> class std::auto_ptr’ is deprecated [-Wdeprecated-declarations]
     shared_ptr( std::auto_ptr<Y> && r ): px(r.get()), pn()`

**Comment by bassosimone** [comment]
Just ignore those warnings: they are emitted while compiling yaml-cpp code, which is still using the old C++03 conventions. They will vanish when we pull recent changes to make yaml-cpp C++11 compatible and dispose of its (now unneeded) boost dependency. (In any case, yaml-cpp is not going to last very long as a dependency, since we're using it for OONI reports and OONI is being switched over to use JSON in all places for efficiency.)
