### ISSUE TITLE
Add optional parameter to net::connect()

### ISSUE THREAD

**Issue by DavideAllavena** [measurement-kit/measurement-kit#238]
net::connect() should accept the optional parameter poller*.

We can do this either with the function overloading or adding a parameter with a default value (`nullptr` in this case).

**Comment by bassosimone** [comment]
@DavideAllavena I prefer the solution in which there is a parameter with a default value because this is the style in which most of MeasurementKit is already written.

Let me also add to the above that this issue is important for us because having this feature implemented allows Portolan to use MeasurementKit code.
