### ISSUE TITLE
Why building for iOS simulator is not cross compiling?

### ISSUE THREAD

**Issue by bassosimone** [measurement-kit/measurement-kit#616]
Perhaps a stupid question, but -- as noted in #612 -- compiling for the iOS simulator is not detected by configure as cross compiling. I understand that, somehow, this happens because we're building on a Intel processor for an Intel processor. But, at the same time, I was expecting this kind of build to result as cross compilation because we are passing `--host` and `--target` to configure.

**Comment by AntonioLangiu** [comment]
I was expecting the same behavior, but I understood that it is actually not so. The problem is that configure enters in cross compiling mode just if the two variables `--build` and `--host` are different. We are actually not setting the `--build` options and so it is automatically setted up with the result of [config.guess](http://git.savannah.gnu.org/gitweb/?p=config.git;a=blob_plain;f=config.guess;hb=HEAD) that in the case of the iphonesimulator the same than `--host`.

I tried it with my Mac and the output of config.guess is `x86_64-apple-darwin15.4.0`, and it is the same that we set [here](https://github.com/measurement-kit/measurement-kit/blob/master/build/ios/scripts/build_arch.sh#L23). (I don't think the version is checked)

Read [this](https://www.gnu.org/software/autoconf/manual/autoconf-2.69/html_node/Hosts-and-Cross_002dCompilation.html) to get more details.

I don't think this will be an issue for us, but it is a good thing to know if we encounter some problem in the future!
