### ISSUE TITLE
Adding network neutrality tests to measurement-kit

### ISSUE THREAD

**Issue by hellais** [measurement-kit/measurement-kit#703]
Network neutrality violations are also interesting to be assessed and we should explore the possibility of implementing these in MK.

Off the top of my head I see some value in implementing the following:
- neubot DASH test (https://github.com/neubot/neubot-client/tree/master/mod_dash)
- neubot bittorrent test (https://github.com/neubot/neubot-client/tree/master/neubot/bittorrent)

Other interesting approaches that are protocol neutral:
- glasnost (https://github.com/marcelscode/glasnost)
- Differentiation Detector (https://github.com/arashmolavi/DifferentiationDetector) (mentioned by @phillipa)

**Comment by phillipa** [comment]
Yup.

I’d love to see the diff detector idea ported to a more general platform. Might get an MS student on it once I move.

-P

**Comment by bassosimone** [comment]
Update:

1. DASH is now part of measurement-kit

2. bittorrent: it would be smart to have an uTP based test rather than a TCP based one (see #1379)

3. for other reasons, I will soon port part of the Glasnost engine into MK and perform some changes to it that however should not prevent it from being used as originally intended

4. from a cursory look, it seems to me that also Differentiation Detector is based on the concept of replying packet traces, so I guess having a modified Glasnost in tree would also help in this respect

**Comment by bassosimone** [comment]
We won't be working on this. I am closing this issue now.
