### ISSUE TITLE
ooni: report_id field is not set inside of measurement-kit ooni reports

### ISSUE THREAD

**Issue by hellais** [measurement-kit/measurement-kit#905]
Currently there is no `report_id` key (that is the value returned by the collector when a report is created) when writing reports to disk or when sending them to a collector.

**Comment by bassosimone** [comment]
This will be partially addressed in #927 (for stable) and in a future pull request (for master). In stable we can only make sure we submit a correct report but we cannot make sure we write on disk a correct report because this change would actually break the API, which I don't want to do on stable.

As such, I'm moving this issue to release-0.4.0 milestone.
